"""module_h_step00_persistence_schema

Revision ID: 04102d744524
Revises: d4e5f6a1b2c3
Create Date: 2026-09-01 10:24:23.039188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.module_d


# revision identifiers, used by Alembic.
revision: str = '04102d744524'
down_revision: Union[str, None] = 'd4e5f6a1b2c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_action_outbox',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.Enum('UPLOAD_DOCUMENT', 'CONTEST_DRAFT', 'CONTEST_SUBMIT', 'ACCEPT', name='externalactiontype'), nullable=False),
    sa.Column('aggregate_id', sa.UUID(), nullable=False),
    sa.Column('payload_json', app.models.module_d.JSONVariant(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'SENT', 'FAILED', name='outboxstatus'), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_external_action_outbox_case_id'), 'external_action_outbox', ['case_id'], unique=False)
    op.create_table('external_action_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('outbox_id', sa.UUID(), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('request_metadata', app.models.module_d.JSONVariant(), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('response_metadata', app.models.module_d.JSONVariant(), nullable=True),
    sa.Column('error_code', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['outbox_id'], ['external_action_outbox.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_external_action_attempts_outbox_id'), 'external_action_attempts', ['outbox_id'], unique=False)
    op.create_table('razorpay_document_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('razorpay_document_id', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('external_response_json', app.models.module_d.JSONVariant(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['evidence_documents.document_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('razorpay_document_id')
    )
    op.create_index(op.f('ix_razorpay_document_links_document_id'), 'razorpay_document_links', ['document_id'], unique=False)
    op.create_table('review_queue_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('prediction_id', sa.UUID(), nullable=False),
    sa.Column('draft_id', sa.UUID(), nullable=True),
    sa.Column('priority_score', sa.Numeric(), nullable=False),
    sa.Column('queue_status', sa.Enum('PENDING', 'ASSIGNED', 'DONE', name='queuestatus'), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('respond_by', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['app_users.user_id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.ForeignKeyConstraint(['draft_id'], ['generated_drafts.id'], ),
    sa.ForeignKeyConstraint(['prediction_id'], ['risk_predictions.prediction_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_queue_items_assigned_to'), 'review_queue_items', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_review_queue_items_case_id'), 'review_queue_items', ['case_id'], unique=False)
    op.create_index(op.f('ix_review_queue_items_draft_id'), 'review_queue_items', ['draft_id'], unique=False)
    op.create_index(op.f('ix_review_queue_items_prediction_id'), 'review_queue_items', ['prediction_id'], unique=False)
    op.create_table('review_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('queue_item_id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Enum('APPROVE_CONTEST', 'APPROVE_ACCEPT', 'REQUEST_MORE_EVIDENCE', 'EDIT_DRAFT', 'REJECT_RECOMMENDATION', 'ESCALATE', 'ACCEPT', 'REQUEST_MORE', name='reviewactionenum'), nullable=False),
    sa.Column('override_reason_code', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('draft_revision_json', app.models.module_d.JSONVariant(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.ForeignKeyConstraint(['queue_item_id'], ['review_queue_items.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['app_users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_actions_case_id'), 'review_actions', ['case_id'], unique=False)
    op.create_index(op.f('ix_review_actions_queue_item_id'), 'review_actions', ['queue_item_id'], unique=False)
    op.create_index(op.f('ix_review_actions_reviewer_id'), 'review_actions', ['reviewer_id'], unique=False)
    op.create_table('contest_packages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('review_action_id', sa.UUID(), nullable=False),
    sa.Column('draft_id', sa.UUID(), nullable=False),
    sa.Column('contest_amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('package_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'APPROVED', 'SUBMITTED', 'FAILED', name='contestpackagestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.ForeignKeyConstraint(['draft_id'], ['generated_drafts.id'], ),
    sa.ForeignKeyConstraint(['review_action_id'], ['review_actions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contest_packages_case_id'), 'contest_packages', ['case_id'], unique=False)
    op.create_index(op.f('ix_contest_packages_draft_id'), 'contest_packages', ['draft_id'], unique=False)
    op.create_index(op.f('ix_contest_packages_review_action_id'), 'contest_packages', ['review_action_id'], unique=False)
    op.create_table('contest_package_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contest_package_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('razorpay_evidence_field', sa.String(length=255), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contest_package_id'], ['contest_packages.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['evidence_documents.document_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contest_package_documents_contest_package_id'), 'contest_package_documents', ['contest_package_id'], unique=False)
    op.create_index(op.f('ix_contest_package_documents_document_id'), 'contest_package_documents', ['document_id'], unique=False)
    op.create_table('contest_submissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contest_package_id', sa.UUID(), nullable=False),
    sa.Column('external_dispute_id', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('external_status', sa.String(length=255), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('razorpay_evidence_json', app.models.module_d.JSONVariant(), nullable=False),
    sa.Column('response_snapshot', app.models.module_d.JSONVariant(), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'FAILED', 'PENDING', name='submissionstatus'), nullable=False),
    sa.ForeignKeyConstraint(['contest_package_id'], ['contest_packages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contest_submissions_contest_package_id'), 'contest_submissions', ['contest_package_id'], unique=False)
    op.create_table('dispute_outcomes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('prediction_id', sa.UUID(), nullable=True),
    sa.Column('contest_submission_id', sa.UUID(), nullable=True),
    sa.Column('outcome', sa.Enum('WON', 'LOST', 'CLOSED', 'UNDER_REVIEW', name='disputeoutcomeenum'), nullable=False),
    sa.Column('amount_deducted_minor', sa.BigInteger(), nullable=True),
    sa.Column('source_event_id', sa.String(length=255), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.ForeignKeyConstraint(['contest_submission_id'], ['contest_submissions.id'], ),
    sa.ForeignKeyConstraint(['prediction_id'], ['risk_predictions.prediction_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispute_outcomes_case_id'), 'dispute_outcomes', ['case_id'], unique=False)
    op.create_index(op.f('ix_dispute_outcomes_contest_submission_id'), 'dispute_outcomes', ['contest_submission_id'], unique=False)
    op.create_index(op.f('ix_dispute_outcomes_prediction_id'), 'dispute_outcomes', ['prediction_id'], unique=False)
    op.create_table('curated_feedback_labels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('outcome_id', sa.UUID(), nullable=True),
    sa.Column('label_name', sa.String(length=255), nullable=False),
    sa.Column('label_value', sa.String(length=255), nullable=False),
    sa.Column('label_quality', sa.Enum('GOLD', 'SILVER', 'SYNTHETIC', name='labelquality'), nullable=False),
    sa.Column('curated_by', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('approved_for_training', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.ForeignKeyConstraint(['curated_by'], ['app_users.user_id'], ),
    sa.ForeignKeyConstraint(['outcome_id'], ['dispute_outcomes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curated_feedback_labels_case_id'), 'curated_feedback_labels', ['case_id'], unique=False)
    op.create_index(op.f('ix_curated_feedback_labels_curated_by'), 'curated_feedback_labels', ['curated_by'], unique=False)
    op.create_index(op.f('ix_curated_feedback_labels_outcome_id'), 'curated_feedback_labels', ['outcome_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_curated_feedback_labels_outcome_id'), table_name='curated_feedback_labels')
    op.drop_index(op.f('ix_curated_feedback_labels_curated_by'), table_name='curated_feedback_labels')
    op.drop_index(op.f('ix_curated_feedback_labels_case_id'), table_name='curated_feedback_labels')
    op.drop_table('curated_feedback_labels')
    op.drop_index(op.f('ix_dispute_outcomes_prediction_id'), table_name='dispute_outcomes')
    op.drop_index(op.f('ix_dispute_outcomes_contest_submission_id'), table_name='dispute_outcomes')
    op.drop_index(op.f('ix_dispute_outcomes_case_id'), table_name='dispute_outcomes')
    op.drop_table('dispute_outcomes')
    op.drop_index(op.f('ix_contest_submissions_contest_package_id'), table_name='contest_submissions')
    op.drop_table('contest_submissions')
    op.drop_index(op.f('ix_contest_package_documents_document_id'), table_name='contest_package_documents')
    op.drop_index(op.f('ix_contest_package_documents_contest_package_id'), table_name='contest_package_documents')
    op.drop_table('contest_package_documents')
    op.drop_index(op.f('ix_contest_packages_review_action_id'), table_name='contest_packages')
    op.drop_index(op.f('ix_contest_packages_draft_id'), table_name='contest_packages')
    op.drop_index(op.f('ix_contest_packages_case_id'), table_name='contest_packages')
    op.drop_table('contest_packages')
    op.drop_index(op.f('ix_review_actions_reviewer_id'), table_name='review_actions')
    op.drop_index(op.f('ix_review_actions_queue_item_id'), table_name='review_actions')
    op.drop_index(op.f('ix_review_actions_case_id'), table_name='review_actions')
    op.drop_table('review_actions')
    op.drop_index(op.f('ix_review_queue_items_prediction_id'), table_name='review_queue_items')
    op.drop_index(op.f('ix_review_queue_items_draft_id'), table_name='review_queue_items')
    op.drop_index(op.f('ix_review_queue_items_case_id'), table_name='review_queue_items')
    op.drop_index(op.f('ix_review_queue_items_assigned_to'), table_name='review_queue_items')
    op.drop_table('review_queue_items')
    op.drop_index(op.f('ix_razorpay_document_links_document_id'), table_name='razorpay_document_links')
    op.drop_table('razorpay_document_links')
    op.drop_index(op.f('ix_external_action_attempts_outbox_id'), table_name='external_action_attempts')
    op.drop_table('external_action_attempts')
    op.drop_index(op.f('ix_external_action_outbox_case_id'), table_name='external_action_outbox')
    op.drop_table('external_action_outbox')
    # ### end Alembic commands ###
