"""add_payment_network

Revision ID: 278d2d4855bb
Revises: ae69c0716354
Create Date: 2026-08-29 22:39:27.748315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '278d2d4855bb'
down_revision: Union[str, None] = 'ae69c0716354'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('network', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'network')
    # ### end Alembic commands ###
