"""module_a_tables

Revision ID: 3cfdc4c4c42d
Revises: e03fdb0295a5
Create Date: 2026-08-28 15:50:27.627023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cfdc4c4c42d'
down_revision: Union[str, None] = 'e03fdb0295a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disputes',
    sa.Column('dispute_pk', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('external_dispute_id', sa.String(length=120), nullable=False),
    sa.Column('payment_id', sa.String(length=120), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('reason_code', sa.String(length=100), nullable=False),
    sa.Column('phase', sa.String(length=60), nullable=True),
    sa.Column('status', sa.String(length=60), nullable=False),
    sa.Column('dispute_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('respond_by', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.PrimaryKeyConstraint('dispute_pk'),
    sa.UniqueConstraint('case_id')
    )
    op.create_index(op.f('ix_disputes_external_dispute_id'), 'disputes', ['external_dispute_id'], unique=False)
    op.create_index(op.f('ix_disputes_payment_id'), 'disputes', ['payment_id'], unique=False)
    op.create_index(op.f('ix_disputes_reason_code'), 'disputes', ['reason_code'], unique=False)
    op.create_index(op.f('ix_disputes_respond_by'), 'disputes', ['respond_by'], unique=False)
    op.create_index(op.f('ix_disputes_status'), 'disputes', ['status'], unique=False)
    op.create_table('webhook_events',
    sa.Column('webhook_event_pk', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('external_event_id', sa.String(length=120), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('signature_verified', sa.Boolean(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.PrimaryKeyConstraint('webhook_event_pk'),
    sa.UniqueConstraint('external_event_id')
    )
    op.create_index(op.f('ix_webhook_events_event_type'), 'webhook_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_webhook_events_received_at'), 'webhook_events', ['received_at'], unique=False)
    op.create_table('dispute_events',
    sa.Column('dispute_event_pk', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('external_event_id', sa.String(length=120), nullable=False),
    sa.Column('old_status', sa.String(length=60), nullable=True),
    sa.Column('new_status', sa.String(length=60), nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_transition', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.ForeignKeyConstraint(['external_event_id'], ['webhook_events.external_event_id'], ),
    sa.PrimaryKeyConstraint('dispute_event_pk')
    )
    op.create_index(op.f('ix_dispute_events_case_id'), 'dispute_events', ['case_id'], unique=False)
    op.create_index(op.f('ix_dispute_events_event_time'), 'dispute_events', ['event_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dispute_events_event_time'), table_name='dispute_events')
    op.drop_index(op.f('ix_dispute_events_case_id'), table_name='dispute_events')
    op.drop_table('dispute_events')
    op.drop_index(op.f('ix_webhook_events_received_at'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_event_type'), table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_index(op.f('ix_disputes_status'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_respond_by'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_reason_code'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_payment_id'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_external_dispute_id'), table_name='disputes')
    op.drop_table('disputes')
    # ### end Alembic commands ###
