"""module_d_tables

Revision ID: 4119534d8208
Revises: 610658fe5adf
Create Date: 2026-08-29 15:51:43.730935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.module_d


# revision identifiers, used by Alembic.
revision: str = '4119534d8208'
down_revision: Union[str, None] = '610658fe5adf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_model_versions',
    sa.Column('model_version_id', sa.UUID(), nullable=False),
    sa.Column('component', sa.String(length=40), nullable=False),
    sa.Column('model_name', sa.String(length=120), nullable=False),
    sa.Column('version', sa.String(length=80), nullable=False),
    sa.Column('config_hash', sa.String(length=64), nullable=False),
    sa.Column('artifact_reference', sa.String(length=500), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('model_version_id')
    )
    op.create_index('idx_doc_model_comp_act', 'document_model_versions', ['component', 'active'], unique=False)
    op.create_index(op.f('ix_document_model_versions_component'), 'document_model_versions', ['component'], unique=False)
    op.create_table('case_document_intelligence_status',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('total_safe_documents', sa.Integer(), nullable=False),
    sa.Column('queued_documents', sa.Integer(), nullable=False),
    sa.Column('processed_documents', sa.Integer(), nullable=False),
    sa.Column('successful_documents', sa.Integer(), nullable=False),
    sa.Column('review_required_documents', sa.Integer(), nullable=False),
    sa.Column('failed_documents', sa.Integer(), nullable=False),
    sa.Column('blocking_failures', sa.Integer(), nullable=False),
    sa.Column('overall_status', sa.String(length=30), nullable=False),
    sa.Column('ready_for_module_e', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.PrimaryKeyConstraint('case_id')
    )
    op.create_index('idx_case_doc_intel_ready_status', 'case_document_intelligence_status', ['ready_for_module_e', 'overall_status'], unique=False)
    op.create_index(op.f('ix_case_document_intelligence_status_overall_status'), 'case_document_intelligence_status', ['overall_status'], unique=False)
    op.create_index(op.f('ix_case_document_intelligence_status_ready_for_module_e'), 'case_document_intelligence_status', ['ready_for_module_e'], unique=False)
    op.create_table('document_processing_jobs',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('job_type', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=160), nullable=False),
    sa.Column('pipeline_version', sa.String(length=60), nullable=False),
    sa.Column('ocr_model_version_id', sa.UUID(), nullable=True),
    sa.Column('extractor_model_version_id', sa.UUID(), nullable=True),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('error_message_masked', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['evidence_documents.document_id'], ),
    sa.ForeignKeyConstraint(['extractor_model_version_id'], ['document_model_versions.model_version_id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.merchant_id'], ),
    sa.ForeignKeyConstraint(['ocr_model_version_id'], ['document_model_versions.model_version_id'], ),
    sa.PrimaryKeyConstraint('job_id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('idx_doc_jobs_case_status', 'document_processing_jobs', ['case_id', 'status'], unique=False)
    op.create_index('idx_doc_jobs_document_status', 'document_processing_jobs', ['document_id', 'status'], unique=False)
    op.create_index(op.f('ix_document_processing_jobs_case_id'), 'document_processing_jobs', ['case_id'], unique=False)
    op.create_index(op.f('ix_document_processing_jobs_document_id'), 'document_processing_jobs', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_processing_jobs_error_code'), 'document_processing_jobs', ['error_code'], unique=False)
    op.create_index(op.f('ix_document_processing_jobs_merchant_id'), 'document_processing_jobs', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_document_processing_jobs_status'), 'document_processing_jobs', ['status'], unique=False)
    op.create_table('document_extractions',
    sa.Column('extraction_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('expected_evidence_type', sa.String(length=60), nullable=False),
    sa.Column('detected_document_type', sa.String(length=60), nullable=True),
    sa.Column('type_match_status', sa.String(length=30), nullable=False),
    sa.Column('extraction_status', sa.String(length=30), nullable=False),
    sa.Column('schema_version', sa.String(length=40), nullable=False),
    sa.Column('extracted_json', app.models.module_d.JSONVariant(), nullable=False),
    sa.Column('overall_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('requires_review', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['evidence_documents.document_id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['document_processing_jobs.job_id'], ),
    sa.PrimaryKeyConstraint('extraction_id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_index('idx_doc_ext_doc_created', 'document_extractions', ['document_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_document_extractions_case_id'), 'document_extractions', ['case_id'], unique=False)
    op.create_index(op.f('ix_document_extractions_detected_document_type'), 'document_extractions', ['detected_document_type'], unique=False)
    op.create_index(op.f('ix_document_extractions_document_id'), 'document_extractions', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_extractions_extraction_status'), 'document_extractions', ['extraction_status'], unique=False)
    op.create_table('document_pages',
    sa.Column('page_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('native_text_used', sa.Boolean(), nullable=False),
    sa.Column('page_artifact_key', sa.String(length=500), nullable=True),
    sa.Column('ocr_text_object_key', sa.String(length=500), nullable=True),
    sa.Column('layout_object_key', sa.String(length=500), nullable=True),
    sa.Column('width_px', sa.Integer(), nullable=True),
    sa.Column('height_px', sa.Integer(), nullable=True),
    sa.Column('rotation_degrees', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('preprocessing_json', app.models.module_d.JSONVariant(), nullable=False),
    sa.Column('ocr_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['evidence_documents.document_id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['document_processing_jobs.job_id'], ),
    sa.PrimaryKeyConstraint('page_id'),
    sa.UniqueConstraint('job_id', 'page_number', name='uq_document_pages_job_page')
    )
    op.create_index(op.f('ix_document_pages_document_id'), 'document_pages', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_pages_job_id'), 'document_pages', ['job_id'], unique=False)
    op.create_table('document_quality_assessments',
    sa.Column('quality_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('blur_score', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('skew_degrees', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('resolution_dpi', sa.Integer(), nullable=True),
    sa.Column('readable_ratio', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('ocr_coverage_ratio', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('cropping_suspected', sa.Boolean(), nullable=False),
    sa.Column('low_contrast', sa.Boolean(), nullable=False),
    sa.Column('quality_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('quality_grade', sa.String(length=20), nullable=True),
    sa.Column('quality_flags', app.models.module_d.JSONVariant(), nullable=False),
    sa.Column('assessed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['evidence_documents.document_id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['document_processing_jobs.job_id'], ),
    sa.PrimaryKeyConstraint('quality_id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_index(op.f('ix_document_quality_assessments_document_id'), 'document_quality_assessments', ['document_id'], unique=False)
    op.create_table('extracted_fields',
    sa.Column('field_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('extraction_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('value_type', sa.String(length=30), nullable=False),
    sa.Column('canonical_value_text', sa.String(), nullable=True),
    sa.Column('numeric_value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('date_value', sa.DateTime(), nullable=True),
    sa.Column('timestamp_value', sa.DateTime(timezone=True), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=True),
    sa.Column('normalized_hash', sa.String(length=64), nullable=True),
    sa.Column('raw_value_masked', sa.String(length=500), nullable=True),
    sa.Column('field_confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('source_bbox', app.models.module_d.JSONVariant(), nullable=True),
    sa.Column('source_text_hash', sa.String(length=64), nullable=True),
    sa.Column('review_status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['evidence_documents.document_id'], ),
    sa.ForeignKeyConstraint(['extraction_id'], ['document_extractions.extraction_id'], ),
    sa.PrimaryKeyConstraint('field_id')
    )
    op.create_index('idx_ext_fields_doc_name', 'extracted_fields', ['document_id', 'field_name'], unique=False)
    op.create_index('idx_ext_fields_ext_name', 'extracted_fields', ['extraction_id', 'field_name'], unique=False)
    op.create_index(op.f('ix_extracted_fields_document_id'), 'extracted_fields', ['document_id'], unique=False)
    op.create_index(op.f('ix_extracted_fields_extraction_id'), 'extracted_fields', ['extraction_id'], unique=False)
    op.create_index(op.f('ix_extracted_fields_field_name'), 'extracted_fields', ['field_name'], unique=False)
    op.create_index(op.f('ix_extracted_fields_normalized_hash'), 'extracted_fields', ['normalized_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_extracted_fields_normalized_hash'), table_name='extracted_fields')
    op.drop_index(op.f('ix_extracted_fields_field_name'), table_name='extracted_fields')
    op.drop_index(op.f('ix_extracted_fields_extraction_id'), table_name='extracted_fields')
    op.drop_index(op.f('ix_extracted_fields_document_id'), table_name='extracted_fields')
    op.drop_index('idx_ext_fields_ext_name', table_name='extracted_fields')
    op.drop_index('idx_ext_fields_doc_name', table_name='extracted_fields')
    op.drop_table('extracted_fields')
    op.drop_index(op.f('ix_document_quality_assessments_document_id'), table_name='document_quality_assessments')
    op.drop_table('document_quality_assessments')
    op.drop_index(op.f('ix_document_pages_job_id'), table_name='document_pages')
    op.drop_index(op.f('ix_document_pages_document_id'), table_name='document_pages')
    op.drop_table('document_pages')
    op.drop_index(op.f('ix_document_extractions_extraction_status'), table_name='document_extractions')
    op.drop_index(op.f('ix_document_extractions_document_id'), table_name='document_extractions')
    op.drop_index(op.f('ix_document_extractions_detected_document_type'), table_name='document_extractions')
    op.drop_index(op.f('ix_document_extractions_case_id'), table_name='document_extractions')
    op.drop_index('idx_doc_ext_doc_created', table_name='document_extractions')
    op.drop_table('document_extractions')
    op.drop_index(op.f('ix_document_processing_jobs_status'), table_name='document_processing_jobs')
    op.drop_index(op.f('ix_document_processing_jobs_merchant_id'), table_name='document_processing_jobs')
    op.drop_index(op.f('ix_document_processing_jobs_error_code'), table_name='document_processing_jobs')
    op.drop_index(op.f('ix_document_processing_jobs_document_id'), table_name='document_processing_jobs')
    op.drop_index(op.f('ix_document_processing_jobs_case_id'), table_name='document_processing_jobs')
    op.drop_index('idx_doc_jobs_document_status', table_name='document_processing_jobs')
    op.drop_index('idx_doc_jobs_case_status', table_name='document_processing_jobs')
    op.drop_table('document_processing_jobs')
    op.drop_index(op.f('ix_case_document_intelligence_status_ready_for_module_e'), table_name='case_document_intelligence_status')
    op.drop_index(op.f('ix_case_document_intelligence_status_overall_status'), table_name='case_document_intelligence_status')
    op.drop_index('idx_case_doc_intel_ready_status', table_name='case_document_intelligence_status')
    op.drop_table('case_document_intelligence_status')
    op.drop_index(op.f('ix_document_model_versions_component'), table_name='document_model_versions')
    op.drop_index('idx_doc_model_comp_act', table_name='document_model_versions')
    op.drop_table('document_model_versions')
    # ### end Alembic commands ###
