"""module_c_tables

Revision ID: 610658fe5adf
Revises: 9803ead2cb4c
Create Date: 2026-08-28 16:47:12.777846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '610658fe5adf'
down_revision: Union[str, None] = '9803ead2cb4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence_requirements',
    sa.Column('requirement_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('reason_code', sa.String(length=100), nullable=False),
    sa.Column('evidence_type', sa.String(length=60), nullable=False),
    sa.Column('requirement_level', sa.Enum('REQUIRED', 'RECOMMENDED', 'OPTIONAL', name='requirementlevel'), nullable=False),
    sa.Column('policy_version', sa.String(length=40), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('requirement_id')
    )
    op.create_index(op.f('ix_evidence_requirements_reason_code'), 'evidence_requirements', ['reason_code'], unique=False)
    op.create_table('case_evidence_status',
    sa.Column('case_evidence_status_pk', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('reason_code', sa.String(length=100), nullable=False),
    sa.Column('required_count', sa.Integer(), nullable=False),
    sa.Column('available_required_count', sa.Integer(), nullable=False),
    sa.Column('missing_required', sa.JSON(), nullable=False),
    sa.Column('coverage_ratio', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.PrimaryKeyConstraint('case_evidence_status_pk')
    )
    op.create_index(op.f('ix_case_evidence_status_case_id'), 'case_evidence_status', ['case_id'], unique=True)
    op.create_table('evidence_documents',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('evidence_type', sa.String(length=60), nullable=False),
    sa.Column('object_key', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('scan_status', sa.Enum('PENDING', 'CLEAN', 'INFECTED', 'FAILED', name='scanstatus'), nullable=False),
    sa.Column('processing_status', sa.Enum('UPLOADED', 'QUARANTINED', 'READY_FOR_OCR', 'REJECTED', 'CORRUPTED', 'SCAN_FAILED', name='evidenceprocessingstatus'), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.merchant_id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['app_users.user_id'], ),
    sa.PrimaryKeyConstraint('document_id'),
    sa.UniqueConstraint('case_id', 'sha256', name='uq_evidence_case_sha256'),
    sa.UniqueConstraint('object_key')
    )
    op.create_index(op.f('ix_evidence_documents_case_id'), 'evidence_documents', ['case_id'], unique=False)
    op.create_index(op.f('ix_evidence_documents_evidence_type'), 'evidence_documents', ['evidence_type'], unique=False)
    op.create_index(op.f('ix_evidence_documents_merchant_id'), 'evidence_documents', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_evidence_documents_processing_status'), 'evidence_documents', ['processing_status'], unique=False)
    op.create_index(op.f('ix_evidence_documents_sha256'), 'evidence_documents', ['sha256'], unique=False)
    op.create_table('evidence_access_events',
    sa.Column('evidence_event_pk', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('result', sa.String(length=30), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['evidence_documents.document_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_users.user_id'], ),
    sa.PrimaryKeyConstraint('evidence_event_pk')
    )
    op.create_index(op.f('ix_evidence_access_events_case_id'), 'evidence_access_events', ['case_id'], unique=False)
    op.create_index(op.f('ix_evidence_access_events_document_id'), 'evidence_access_events', ['document_id'], unique=False)
    op.create_index(op.f('ix_evidence_access_events_occurred_at'), 'evidence_access_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_evidence_access_events_request_id'), 'evidence_access_events', ['request_id'], unique=False)
    op.create_table('malware_scan_results',
    sa.Column('scan_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('scanner', sa.String(length=80), nullable=False),
    sa.Column('scanner_version', sa.String(length=80), nullable=True),
    sa.Column('scan_status', sa.Enum('PENDING', 'CLEAN', 'INFECTED', 'FAILED', name='scanstatus'), nullable=False),
    sa.Column('signature_name', sa.String(length=255), nullable=True),
    sa.Column('scanned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['evidence_documents.document_id'], ),
    sa.PrimaryKeyConstraint('scan_id')
    )
    op.create_index(op.f('ix_malware_scan_results_document_id'), 'malware_scan_results', ['document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_malware_scan_results_document_id'), table_name='malware_scan_results')
    op.drop_table('malware_scan_results')
    op.drop_index(op.f('ix_evidence_access_events_request_id'), table_name='evidence_access_events')
    op.drop_index(op.f('ix_evidence_access_events_occurred_at'), table_name='evidence_access_events')
    op.drop_index(op.f('ix_evidence_access_events_document_id'), table_name='evidence_access_events')
    op.drop_index(op.f('ix_evidence_access_events_case_id'), table_name='evidence_access_events')
    op.drop_table('evidence_access_events')
    op.drop_index(op.f('ix_evidence_documents_sha256'), table_name='evidence_documents')
    op.drop_index(op.f('ix_evidence_documents_processing_status'), table_name='evidence_documents')
    op.drop_index(op.f('ix_evidence_documents_merchant_id'), table_name='evidence_documents')
    op.drop_index(op.f('ix_evidence_documents_evidence_type'), table_name='evidence_documents')
    op.drop_index(op.f('ix_evidence_documents_case_id'), table_name='evidence_documents')
    op.drop_table('evidence_documents')
    op.drop_index(op.f('ix_case_evidence_status_case_id'), table_name='case_evidence_status')
    op.drop_table('case_evidence_status')
    op.drop_index(op.f('ix_evidence_requirements_reason_code'), table_name='evidence_requirements')
    op.drop_table('evidence_requirements')
    # ### end Alembic commands ###
