"""module_f_step18

Revision ID: 88315f51b049
Revises: bef18018ed1c
Create Date: 2026-08-31 20:36:03.011775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.module_d


# revision identifiers, used by Alembic.
revision: str = '88315f51b049'
down_revision: Union[str, None] = 'bef18018ed1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml_datasets',
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('dataset_version', sa.String(length=50), nullable=True),
    sa.Column('label_definition', sa.Text(), nullable=True),
    sa.Column('feature_schema_version', sa.String(length=100), nullable=True),
    sa.Column('label_policy_version', sa.String(length=100), nullable=True),
    sa.Column('generator_version', sa.String(length=100), nullable=True),
    sa.Column('frozen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('checksum', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('dataset_id')
    )
    op.create_table('model_versions',
    sa.Column('model_version_id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(length=200), nullable=True),
    sa.Column('algorithm', sa.String(length=100), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=True),
    sa.Column('feature_schema_version', sa.String(length=100), nullable=True),
    sa.Column('artifact_uri', sa.Text(), nullable=True),
    sa.Column('preprocessing_hash', sa.String(length=255), nullable=True),
    sa.Column('calibrator_uri', sa.Text(), nullable=True),
    sa.Column('code_commit', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['ml_datasets.dataset_id'], ),
    sa.PrimaryKeyConstraint('model_version_id')
    )
    op.create_table('ml_labels',
    sa.Column('label_id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('target_name', sa.String(length=100), nullable=False),
    sa.Column('label_value', sa.String(length=100), nullable=False),
    sa.Column('label_source', sa.String(length=100), nullable=False),
    sa.Column('label_policy_version', sa.String(length=100), nullable=True),
    sa.Column('reviewer_generator', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.PrimaryKeyConstraint('label_id')
    )
    op.create_index(op.f('ix_ml_labels_case_id'), 'ml_labels', ['case_id'], unique=False)
    op.create_table('model_decision_policies',
    sa.Column('policy_id', sa.UUID(), nullable=False),
    sa.Column('model_version_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('policy_version', sa.String(length=100), nullable=True),
    sa.Column('t_accept', sa.Numeric(), nullable=True),
    sa.Column('t_contest', sa.Numeric(), nullable=True),
    sa.Column('c_fp', sa.Numeric(), nullable=True),
    sa.Column('c_fn', sa.Numeric(), nullable=True),
    sa.Column('c_review', sa.Numeric(), nullable=True),
    sa.Column('hard_block_rules', app.models.module_d.JSONVariant(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.model_version_id'], ),
    sa.PrimaryKeyConstraint('policy_id')
    )
    op.create_table('model_training_runs',
    sa.Column('training_run_id', sa.UUID(), nullable=False),
    sa.Column('model_version_id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=True),
    sa.Column('hyperparameters_json', app.models.module_d.JSONVariant(), nullable=True),
    sa.Column('random_seed', sa.Integer(), nullable=True),
    sa.Column('environment_json', app.models.module_d.JSONVariant(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['ml_datasets.dataset_id'], ),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.model_version_id'], ),
    sa.PrimaryKeyConstraint('training_run_id')
    )
    op.create_table('model_metrics',
    sa.Column('metric_id', sa.UUID(), nullable=False),
    sa.Column('training_run_id', sa.UUID(), nullable=True),
    sa.Column('model_version_id', sa.UUID(), nullable=True),
    sa.Column('split', sa.String(length=50), nullable=False),
    sa.Column('slice_name', sa.String(length=100), nullable=True),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('metric_value', sa.Numeric(), nullable=False),
    sa.Column('metric_context', app.models.module_d.JSONVariant(), nullable=True),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.model_version_id'], ),
    sa.ForeignKeyConstraint(['training_run_id'], ['model_training_runs.training_run_id'], ),
    sa.PrimaryKeyConstraint('metric_id')
    )
    op.create_table('ml_dataset_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('feature_snapshot_id', sa.UUID(), nullable=False),
    sa.Column('label_id', sa.UUID(), nullable=True),
    sa.Column('label', sa.String(length=50), nullable=True),
    sa.Column('label_source', sa.String(length=100), nullable=True),
    sa.Column('split', sa.String(length=50), nullable=False),
    sa.Column('group_key', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.ForeignKeyConstraint(['dataset_id'], ['ml_datasets.dataset_id'], ),
    sa.ForeignKeyConstraint(['feature_snapshot_id'], ['case_feature_snapshots.id'], ),
    sa.ForeignKeyConstraint(['label_id'], ['ml_labels.label_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_dataset_members_dataset_id'), 'ml_dataset_members', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_ml_dataset_members_split'), 'ml_dataset_members', ['split'], unique=False)
    op.create_table('risk_predictions',
    sa.Column('prediction_id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('feature_snapshot_id', sa.UUID(), nullable=False),
    sa.Column('model_version_id', sa.UUID(), nullable=False),
    sa.Column('decision_policy_id', sa.UUID(), nullable=False),
    sa.Column('raw_score', sa.Numeric(), nullable=False),
    sa.Column('calibrated_probability', sa.Numeric(), nullable=False),
    sa.Column('recommendation', sa.String(length=50), nullable=False),
    sa.Column('hard_block', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.ForeignKeyConstraint(['decision_policy_id'], ['model_decision_policies.policy_id'], ),
    sa.ForeignKeyConstraint(['feature_snapshot_id'], ['case_feature_snapshots.id'], ),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.model_version_id'], ),
    sa.PrimaryKeyConstraint('prediction_id'),
    sa.UniqueConstraint('idempotency_key', name='uq_risk_predictions_idempotency_key')
    )
    op.create_index(op.f('ix_risk_predictions_case_id'), 'risk_predictions', ['case_id'], unique=False)
    op.create_index(op.f('ix_risk_predictions_created_at'), 'risk_predictions', ['created_at'], unique=False)
    op.create_table('prediction_explanations',
    sa.Column('explanation_id', sa.UUID(), nullable=False),
    sa.Column('prediction_id', sa.UUID(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('feature_name', sa.String(length=255), nullable=False),
    sa.Column('feature_value_safe', app.models.module_d.JSONVariant(), nullable=True),
    sa.Column('shap_value', sa.Numeric(), nullable=True),
    sa.Column('direction', sa.String(length=50), nullable=True),
    sa.Column('display_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['prediction_id'], ['risk_predictions.prediction_id'], ),
    sa.PrimaryKeyConstraint('explanation_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prediction_explanations')
    op.drop_index(op.f('ix_risk_predictions_created_at'), table_name='risk_predictions')
    op.drop_index(op.f('ix_risk_predictions_case_id'), table_name='risk_predictions')
    op.drop_table('risk_predictions')
    op.drop_index(op.f('ix_ml_dataset_members_split'), table_name='ml_dataset_members')
    op.drop_index(op.f('ix_ml_dataset_members_dataset_id'), table_name='ml_dataset_members')
    op.drop_table('ml_dataset_members')
    op.drop_table('model_metrics')
    op.drop_table('model_training_runs')
    op.drop_table('model_decision_policies')
    op.drop_index(op.f('ix_ml_labels_case_id'), table_name='ml_labels')
    op.drop_table('ml_labels')
    op.drop_table('model_versions')
    op.drop_table('ml_datasets')
    # ### end Alembic commands ###
