"""module_b_tables

Revision ID: 9803ead2cb4c
Revises: 3cfdc4c4c42d
Create Date: 2026-08-28 16:16:29.977161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9803ead2cb4c'
down_revision: Union[str, None] = '3cfdc4c4c42d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_enrichment',
    sa.Column('enrichment_pk', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('payment_complete', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('order_complete', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('shipment_complete', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('refund_complete', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('customer_complete', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('overall_complete', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('consistency_flags', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('timeline_json', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.PrimaryKeyConstraint('enrichment_pk')
    )
    op.create_index(op.f('ix_case_enrichment_case_id'), 'case_enrichment', ['case_id'], unique=False)
    op.create_table('customer_history',
    sa.Column('customer_history_pk', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('customer_ref_hash', sa.String(length=64), nullable=True),
    sa.Column('account_age_days', sa.Integer(), nullable=True),
    sa.Column('previous_order_count', sa.Integer(), nullable=True),
    sa.Column('previous_dispute_count', sa.Integer(), nullable=True),
    sa.Column('previous_refund_count', sa.Integer(), nullable=True),
    sa.Column('refund_rate', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('dispute_rate', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.PrimaryKeyConstraint('customer_history_pk'),
    sa.UniqueConstraint('case_id', name='uq_customer_history_case')
    )
    op.create_index(op.f('ix_customer_history_case_id'), 'customer_history', ['case_id'], unique=False)
    op.create_index(op.f('ix_customer_history_customer_ref_hash'), 'customer_history', ['customer_ref_hash'], unique=False)
    op.create_table('orders',
    sa.Column('order_pk', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('external_order_id', sa.String(length=120), nullable=False),
    sa.Column('merchant_order_ref', sa.String(length=120), nullable=True),
    sa.Column('order_amount_minor', sa.BigInteger(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('order_status', sa.String(length=50), nullable=True),
    sa.Column('customer_ref_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at_source', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.PrimaryKeyConstraint('order_pk'),
    sa.UniqueConstraint('case_id', 'external_order_id', name='uq_orders_case_ext_order')
    )
    op.create_index(op.f('ix_orders_case_id'), 'orders', ['case_id'], unique=False)
    op.create_index(op.f('ix_orders_customer_ref_hash'), 'orders', ['customer_ref_hash'], unique=False)
    op.create_index(op.f('ix_orders_external_order_id'), 'orders', ['external_order_id'], unique=False)
    op.create_index(op.f('ix_orders_merchant_order_ref'), 'orders', ['merchant_order_ref'], unique=False)
    op.create_table('payments',
    sa.Column('payment_pk', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('external_payment_id', sa.String(length=120), nullable=False),
    sa.Column('external_order_id', sa.String(length=120), nullable=True),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=True),
    sa.Column('captured', sa.Boolean(), nullable=True),
    sa.Column('created_at_source', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.PrimaryKeyConstraint('payment_pk'),
    sa.UniqueConstraint('case_id', 'external_payment_id', name='uq_payments_case_ext_pay')
    )
    op.create_index(op.f('ix_payments_case_id'), 'payments', ['case_id'], unique=False)
    op.create_index(op.f('ix_payments_external_order_id'), 'payments', ['external_order_id'], unique=False)
    op.create_index(op.f('ix_payments_external_payment_id'), 'payments', ['external_payment_id'], unique=False)
    op.create_table('refunds',
    sa.Column('refund_pk', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('external_refund_id', sa.String(length=120), nullable=False),
    sa.Column('external_payment_id', sa.String(length=120), nullable=False),
    sa.Column('refund_amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('refund_reason', sa.String(length=255), nullable=True),
    sa.Column('refund_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.PrimaryKeyConstraint('refund_pk'),
    sa.UniqueConstraint('case_id', 'external_refund_id', name='uq_refunds_case_ext_refund')
    )
    op.create_index(op.f('ix_refunds_case_id'), 'refunds', ['case_id'], unique=False)
    op.create_index(op.f('ix_refunds_external_payment_id'), 'refunds', ['external_payment_id'], unique=False)
    op.create_index(op.f('ix_refunds_external_refund_id'), 'refunds', ['external_refund_id'], unique=False)
    op.create_table('shipments',
    sa.Column('shipment_pk', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('external_order_id', sa.String(length=120), nullable=False),
    sa.Column('shipment_id', sa.String(length=120), nullable=False),
    sa.Column('courier', sa.String(length=100), nullable=True),
    sa.Column('tracking_id', sa.String(length=150), nullable=True),
    sa.Column('dispatch_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_status', sa.String(length=50), nullable=True),
    sa.Column('delivery_address_hash', sa.String(length=64), nullable=True),
    sa.Column('recipient_confirmation', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.PrimaryKeyConstraint('shipment_pk'),
    sa.UniqueConstraint('case_id', 'shipment_id', name='uq_shipments_case_ship')
    )
    op.create_index(op.f('ix_shipments_case_id'), 'shipments', ['case_id'], unique=False)
    op.create_index(op.f('ix_shipments_external_order_id'), 'shipments', ['external_order_id'], unique=False)
    op.create_index(op.f('ix_shipments_shipment_id'), 'shipments', ['shipment_id'], unique=False)
    op.create_index(op.f('ix_shipments_tracking_id'), 'shipments', ['tracking_id'], unique=False)
    # NOTE: Auto-detected alter_column ops for Module A/foundation tables
    # (BIGINT→Integer) have been intentionally removed. The BIGINT types in
    # Postgres are correct; the Integer types in model files are a SQLite
    # test compatibility workaround.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shipments_tracking_id'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_shipment_id'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_external_order_id'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_case_id'), table_name='shipments')
    op.drop_table('shipments')
    op.drop_index(op.f('ix_refunds_external_refund_id'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_external_payment_id'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_case_id'), table_name='refunds')
    op.drop_table('refunds')
    op.drop_index(op.f('ix_payments_external_payment_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_external_order_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_case_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_orders_merchant_order_ref'), table_name='orders')
    op.drop_index(op.f('ix_orders_external_order_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_customer_ref_hash'), table_name='orders')
    op.drop_index(op.f('ix_orders_case_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_customer_history_customer_ref_hash'), table_name='customer_history')
    op.drop_index(op.f('ix_customer_history_case_id'), table_name='customer_history')
    op.drop_table('customer_history')
    op.drop_index(op.f('ix_case_enrichment_case_id'), table_name='case_enrichment')
    op.drop_table('case_enrichment')
    # ### end Alembic commands ###
