"""module_e_step3_tables

Revision ID: a0dfec73e0a7
Revises: 278d2d4855bb
Create Date: 2026-08-29 23:25:37.795044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0dfec73e0a7'
down_revision: Union[str, None] = '278d2d4855bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence_policy_rule_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('policy_version_id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('rule_version_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['policy_version_id'], ['evidence_policy_versions.policy_version_id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['validation_rule_catalog.rule_id'], ),
    sa.ForeignKeyConstraint(['rule_version_id'], ['validation_rule_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('policy_version_id', 'rule_id', name='uq_ev_pol_rule_identity')
    )
    op.create_unique_constraint('uq_case_feature_snapshot_run', 'case_feature_snapshots', ['validation_run_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_case_feature_snapshot_run', 'case_feature_snapshots', type_='unique')
    op.drop_table('evidence_policy_rule_versions')
    # ### end Alembic commands ###
