"""module_e_tables

Revision ID: ae69c0716354
Revises: c830bd6f038b
Create Date: 2026-08-29 22:20:58.789838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app


# revision identifiers, used by Alembic.
revision: str = 'ae69c0716354'
down_revision: Union[str, None] = 'c830bd6f038b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence_policy_versions',
    sa.Column('policy_version_id', sa.UUID(), nullable=False),
    sa.Column('payment_network', sa.String(length=100), nullable=False),
    sa.Column('reason_code', sa.String(length=100), nullable=False),
    sa.Column('phase', sa.String(length=100), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('policy_version_id'),
    sa.UniqueConstraint('payment_network', 'reason_code', 'phase', 'version', name='uq_ev_pol_ver_identity')
    )
    op.create_table('feature_definitions',
    sa.Column('feature_id', sa.UUID(), nullable=False),
    sa.Column('feature_name', sa.String(length=100), nullable=False),
    sa.Column('data_type', sa.Enum('NUMERIC', 'CATEGORICAL', 'BOOLEAN', name='efeaturedatatype'), nullable=False),
    sa.Column('definition', sa.String(), nullable=False),
    sa.Column('source_modules', sa.String(length=100), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('available_at_prediction', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('feature_id'),
    sa.UniqueConstraint('feature_name')
    )
    op.create_table('validation_rule_catalog',
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('rule_code', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('severity_default', sa.Enum('INFO', 'WARN', 'ERROR', name='eruleseverity'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('rule_id'),
    sa.UniqueConstraint('rule_code')
    )
    op.create_table('validation_rule_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('parameters_json', app.models.module_d.JSONVariant(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['validation_rule_catalog.rule_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_id', 'version', name='uq_val_rule_version')
    )
    op.create_table('evidence_validation_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('evidence_version', sa.String(length=100), nullable=False),
    sa.Column('policy_version_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'COMPLETED', 'FAILED', name='evalidationrunstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('idempotency_key', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.ForeignKeyConstraint(['policy_version_id'], ['evidence_policy_versions.policy_version_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('idx_ev_val_run_case_created', 'evidence_validation_runs', ['case_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_evidence_validation_runs_case_id'), 'evidence_validation_runs', ['case_id'], unique=False)
    op.create_table('case_feature_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('validation_run_id', sa.UUID(), nullable=False),
    sa.Column('feature_schema_version', sa.String(length=50), nullable=False),
    sa.Column('features_json', app.models.module_d.JSONVariant(), nullable=False),
    sa.Column('feature_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.ForeignKeyConstraint(['validation_run_id'], ['evidence_validation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cfs_case_current', 'case_feature_snapshots', ['case_id', 'is_current'], unique=False)
    op.create_index('idx_cfs_feature_hash', 'case_feature_snapshots', ['feature_hash'], unique=False)
    op.create_table('cross_source_field_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('validation_run_id', sa.UUID(), nullable=False),
    sa.Column('semantic_field', sa.String(length=100), nullable=False),
    sa.Column('left_source', app.models.module_d.JSONVariant(), nullable=False),
    sa.Column('right_source', app.models.module_d.JSONVariant(), nullable=False),
    sa.Column('match_method', sa.Enum('EXACT', 'FUZZY', 'TOLERANCE', name='ematchmethod'), nullable=False),
    sa.Column('match_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('link_status', sa.Enum('MATCH', 'MISMATCH', 'UNKNOWN', name='elinkstatus'), nullable=False),
    sa.ForeignKeyConstraint(['validation_run_id'], ['evidence_validation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cross_source_field_links_validation_run_id'), 'cross_source_field_links', ['validation_run_id'], unique=False)
    op.create_table('evidence_requirement_assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('validation_run_id', sa.UUID(), nullable=False),
    sa.Column('evidence_type', sa.String(length=100), nullable=False),
    sa.Column('requirement_level', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PRESENT', 'MISSING', 'UNKNOWN', 'UNUSABLE', name='erequirementstate'), nullable=False),
    sa.Column('document_ids', app.models.module_d.JSONVariant(), nullable=True),
    sa.Column('coverage_weight', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['validation_run_id'], ['evidence_validation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_requirement_assessments_validation_run_id'), 'evidence_requirement_assessments', ['validation_run_id'], unique=False)
    op.create_table('evidence_validation_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('validation_run_id', sa.UUID(), nullable=False),
    sa.Column('rule_version_id', sa.UUID(), nullable=False),
    sa.Column('result', sa.Enum('PASS', 'FAIL', 'WARN', 'UNKNOWN', 'NA', name='evalidationresultstate'), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARN', 'ERROR', name='eruleseverity'), nullable=False),
    sa.Column('source_refs', app.models.module_d.JSONVariant(), nullable=True),
    sa.Column('normalized_values', app.models.module_d.JSONVariant(), nullable=True),
    sa.Column('explanation', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['rule_version_id'], ['validation_rule_versions.id'], ),
    sa.ForeignKeyConstraint(['validation_run_id'], ['evidence_validation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ev_val_res_run_result', 'evidence_validation_results', ['validation_run_id', 'result'], unique=False)
    op.create_index('idx_ev_val_res_run_severity', 'evidence_validation_results', ['validation_run_id', 'severity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_ev_val_res_run_severity', table_name='evidence_validation_results')
    op.drop_index('idx_ev_val_res_run_result', table_name='evidence_validation_results')
    op.drop_table('evidence_validation_results')
    op.drop_index(op.f('ix_evidence_requirement_assessments_validation_run_id'), table_name='evidence_requirement_assessments')
    op.drop_table('evidence_requirement_assessments')
    op.drop_index(op.f('ix_cross_source_field_links_validation_run_id'), table_name='cross_source_field_links')
    op.drop_table('cross_source_field_links')
    op.drop_index('idx_cfs_feature_hash', table_name='case_feature_snapshots')
    op.drop_index('idx_cfs_case_current', table_name='case_feature_snapshots')
    op.drop_table('case_feature_snapshots')
    op.drop_index(op.f('ix_evidence_validation_runs_case_id'), table_name='evidence_validation_runs')
    op.drop_index('idx_ev_val_run_case_created', table_name='evidence_validation_runs')
    op.drop_table('evidence_validation_runs')
    op.drop_table('validation_rule_versions')
    op.drop_table('validation_rule_catalog')
    op.drop_table('feature_definitions')
    op.drop_table('evidence_policy_versions')
    # ### end Alembic commands ###
