"""module_h_step04_rbac

Revision ID: b224a21ac9b0
Revises: 04102d744524
Create Date: 2026-09-02 13:08:45.768853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b224a21ac9b0'
down_revision: Union[str, None] = '04102d744524'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    from sqlalchemy.dialects import postgresql
    appuserrole = postgresql.ENUM('MERCHANT_ADMIN', 'RISK_ANALYST', 'APPROVER', 'SYSTEM_WORKER', 'MODEL_MAINTAINER', name='appuserrole')
    appuserrole.create(op.get_bind())
    op.add_column('app_users', sa.Column('role', appuserrole, server_default='APPROVER', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_users', 'role')
    op.execute("DROP TYPE appuserrole")
    # ### end Alembic commands ###
