"""Add Module G tables

Revision ID: bef18018ed1c
Revises: f18d2b28ac78
Create Date: 2026-08-31 16:08:54.574446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
import app.models.module_d


# revision identifiers, used by Alembic.
revision: str = 'bef18018ed1c'
down_revision: Union[str, None] = 'f18d2b28ac78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS vector;')
    op.create_table('knowledge_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=True),
    sa.Column('source_type', sa.Enum('RAZORPAY_POLICY', 'INTERNAL_GUIDELINE', 'REASON_CODE_MAPPING', name='gsourcetype'), nullable=False),
    sa.Column('reason_code', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content_checksum', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'DEPRECATED', name='gsourcestatus'), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata_json', app.models.module_d.JSONVariant(), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.merchant_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_id', 'source_type', 'reason_code', 'version', name='uq_knowledge_source_identity')
    )
    op.create_index(op.f('ix_knowledge_sources_merchant_id'), 'knowledge_sources', ['merchant_id'], unique=False)
    op.create_table('knowledge_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('content_checksum', sa.String(length=64), nullable=False),
    sa.Column('embedding_model', sa.String(length=100), nullable=False),
    sa.Column('embedding_version', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.Column('metadata_json', app.models.module_d.JSONVariant(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['knowledge_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'chunk_index', 'embedding_model', 'embedding_version', name='uq_knowledge_chunk_identity')
    )
    op.create_index(op.f('ix_knowledge_chunks_source_id'), 'knowledge_chunks', ['source_id'], unique=False)
    op.execute("CREATE INDEX idx_knowledge_chunks_embedding ON knowledge_chunks USING hnsw (embedding vector_cosine_ops)")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_chunks_source_id'), table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')
    op.drop_index(op.f('ix_knowledge_sources_merchant_id'), table_name='knowledge_sources')
    op.drop_table('knowledge_sources')
    op.execute('DROP EXTENSION IF EXISTS vector;')
    # ### end Alembic commands ###
