"""module_g_step5_g04

Revision ID: cdeb574db469
Revises: 88315f51b049
Create Date: 2026-08-31 21:31:49.152120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.module_d


# revision identifiers, used by Alembic.
revision: str = 'cdeb574db469'
down_revision: Union[str, None] = '88315f51b049'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rag_retrieval_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('prediction_id', sa.UUID(), nullable=False),
    sa.Column('query_text_redacted', sa.Text(), nullable=False),
    sa.Column('filters_json', app.models.module_d.JSONVariant(), nullable=True),
    sa.Column('top_k', sa.Integer(), nullable=False),
    sa.Column('index_version', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.ForeignKeyConstraint(['prediction_id'], ['risk_predictions.prediction_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rag_retrieval_runs_case_id'), 'rag_retrieval_runs', ['case_id'], unique=False)
    op.create_index(op.f('ix_rag_retrieval_runs_prediction_id'), 'rag_retrieval_runs', ['prediction_id'], unique=False)
    op.create_table('rag_retrieved_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('retrieval_run_id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('similarity_score', sa.Numeric(), nullable=False),
    sa.Column('selected_for_prompt', sa.Boolean(), nullable=False),
    sa.Column('selection_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['knowledge_chunks.id'], ),
    sa.ForeignKeyConstraint(['retrieval_run_id'], ['rag_retrieval_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rag_retrieved_chunks_chunk_id'), 'rag_retrieved_chunks', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_rag_retrieved_chunks_retrieval_run_id'), 'rag_retrieved_chunks', ['retrieval_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rag_retrieved_chunks_retrieval_run_id'), table_name='rag_retrieved_chunks')
    op.drop_index(op.f('ix_rag_retrieved_chunks_chunk_id'), table_name='rag_retrieved_chunks')
    op.drop_table('rag_retrieved_chunks')
    op.drop_index(op.f('ix_rag_retrieval_runs_prediction_id'), table_name='rag_retrieval_runs')
    op.drop_index(op.f('ix_rag_retrieval_runs_case_id'), table_name='rag_retrieval_runs')
    op.drop_table('rag_retrieval_runs')
    # ### end Alembic commands ###
