"""initial_foundation_models

Revision ID: e03fdb0295a5
Revises: 
Create Date: 2026-08-28 09:44:00.199844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e03fdb0295a5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchants',
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('external_merchant_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('merchant_id')
    )
    op.create_index(op.f('ix_merchants_external_merchant_id'), 'merchants', ['external_merchant_id'], unique=True)
    op.create_table('app_users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.merchant_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_app_users_email'), 'app_users', ['email'], unique=True)
    
    # enum type for processing_state
    from sqlalchemy.dialects.postgresql import ENUM
    processing_state = ENUM('RECEIVED', 'VALIDATED', 'INGESTED', 'ENRICHING', 'ENRICHED', 'AWAITING_EVIDENCE', 'EVIDENCE_READY', name='processingstate', create_type=False)
    processing_state.create(op.get_bind(), checkfirst=True)

    op.create_table('cases',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('external_dispute_id', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('processing_state', processing_state, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.merchant_id'], ),
    sa.PrimaryKeyConstraint('case_id')
    )
    op.create_index(op.f('ix_cases_external_dispute_id'), 'cases', ['external_dispute_id'], unique=False)
    
    op.create_table('audit_logs',
    sa.Column('audit_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('details', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_users.user_id'], ),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_index(op.f('ix_audit_logs_audit_id'), 'audit_logs', ['audit_id'], unique=False)
    
    op.create_table('processing_errors',
    sa.Column('error_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('retryable', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.PrimaryKeyConstraint('error_id')
    )
    op.create_index(op.f('ix_processing_errors_error_id'), 'processing_errors', ['error_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processing_errors_error_id'), table_name='processing_errors')
    op.drop_table('processing_errors')
    op.drop_index(op.f('ix_audit_logs_audit_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_cases_external_dispute_id'), table_name='cases')
    op.drop_table('cases')
    op.drop_index(op.f('ix_app_users_email'), table_name='app_users')
    op.drop_table('app_users')
    op.drop_index(op.f('ix_merchants_external_merchant_id'), table_name='merchants')
    op.drop_table('merchants')
    # ### end Alembic commands ###
