"""module_e_step3_enum_states

Revision ID: f18d2b28ac78
Revises: a0dfec73e0a7
Create Date: 2026-08-29 23:30:05.381067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f18d2b28ac78'
down_revision: Union[str, None] = 'a0dfec73e0a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # We must handle adding to PostgreSQL ENUM if the dialect is postgresql
    bind = op.get_bind()
    if bind.dialect.name == 'postgresql':
        op.execute("ALTER TYPE processingstate ADD VALUE IF NOT EXISTS 'D_INTELLIGENCE_READY'")
        op.execute("ALTER TYPE processingstate ADD VALUE IF NOT EXISTS 'E_VALIDATING'")
        op.execute("ALTER TYPE processingstate ADD VALUE IF NOT EXISTS 'EVIDENCE_VALIDATED'")
        op.execute("ALTER TYPE processingstate ADD VALUE IF NOT EXISTS 'FEATURE_READY'")
        
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
